baseurl         = "https://test.jing.com"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Test Site"
  subtitle    = "My First Hugo Site"

  cover       = "upload/photo3.jpeg"
  description = "Jing's awesome site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "Jing Cui"
  fbName = "Tao Lin"
  githubName = "luoshuitaotao"

  logo = ""
  orgName = "UNO"
  orgWebsite = ""
  orgDescription = ""

  author = "Jing"
  authorAvatar = "upload/photo2.jpg"
  authorLocation = "Omaha, NE"
  authorWebsite = "https://luoshuitaotao.github.io"
  authorDescription = "Coder, Student"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Food"
  url = "/categories/food/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95
